name: Format

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the branch code
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Debug environment setup
      - name: Check Node.js and npm versions
        run: |
          node -v
          npm -v

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run Prettier format
      - name: Run Prettier
        run: npm run format

      # Debug formatted files
      - name: List formatted files
        run: git status --short

      # Commit changes (if any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.ref_name }}
